#!/usr/bin/env bash
# Generated By: Claude Code (Claude Opus 4.7)
# SPDX-License-Identifier: Apache-2.0
#
# Fixture tests for build/templates/fabcheck.sh. Each fixture is copied into
# its own working directory under .tmp-fabcheck/ at the repo root, turned
# into a one-commit git repo, and scanned by fabcheck under the active
# environment. The runner asserts that the resulting verdict.json matches
# expected counts / resolution mode / symbol-level findings. Exit 0 if all
# cases pass; exit 1 with a per-case report on failure.
#
# Working directories persist across runs (see common/tmp-dirs.md for the
# .tmp-<slug>/ convention) so failures can be inspected in place — e.g.,
# `cat .tmp-fabcheck/missing-precise/.tmp-fabcheck/verdict.json`. They
# are wiped at the start of each case so results are deterministic.
#
# The "fallback" case requires a PATH without python3. On platforms where a
# local shim for that doesn't execute (notably native Windows), the case is
# skipped with a clear message rather than failing spuriously.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
FABCHECK="$REPO_ROOT/build/templates/fabcheck.sh"
FIXTURES="$SCRIPT_DIR/fixtures"
WORK_ROOT="$REPO_ROOT/.tmp-fabcheck"

if [ ! -f "$FABCHECK" ]; then
    echo "run-tests: fabcheck script not found at $FABCHECK" >&2
    exit 2
fi

# Ensure the working root exists and is git-ignored. The single-line `*`
# gitignore makes the directory fully untracked — including the .gitignore
# itself — while the named directory signals its purpose.
mkdir -p "$WORK_ROOT"
if [ ! -f "$WORK_ROOT/.gitignore" ]; then
    printf '*\n' > "$WORK_ROOT/.gitignore"
fi

pass_count=0
fail_count=0
skip_count=0
FAILED_CASES=()

log_ok()   { echo "  PASS  $1"; pass_count=$((pass_count+1)); }
log_fail() { echo "  FAIL  $1: $2"; fail_count=$((fail_count+1)); FAILED_CASES+=("$1"); }
log_skip() { echo "  SKIP  $1: $2"; skip_count=$((skip_count+1)); }

# Prepare a fixture into its own working directory under .tmp-fabcheck/, run
# fabcheck with any extra args the caller supplies, and echo the working
# directory path. The directory is wiped and recreated each call so reruns
# are deterministic; it is preserved after the run for inspection.
prepare_and_run() {
    local name="$1"; shift
    local work="$WORK_ROOT/$name"
    rm -rf "$work"
    mkdir -p "$work"
    cp -r "$FIXTURES/$name/." "$work/"
    (
        cd "$work"
        git init -q
        git -c core.autocrlf=false -c user.email=test@fabcheck -c user.name=test add -A 2>/dev/null
        git -c core.autocrlf=false -c user.email=test@fabcheck -c user.name=test commit -q -m init >/dev/null
        # Run fabcheck; ignore exit code (we inspect verdict.json for assertions).
        bash "$FABCHECK" "$@" >/dev/null 2>&1 || true
    )
    echo "$work"
}

assert_json() {
    # $1 = verdict path, $2 = jq expression (must return true), $3 = label
    local verdict="$1" expr="$2" label="$3"
    if [ ! -f "$verdict" ]; then
        log_fail "$label" "verdict.json missing at $verdict"
        return
    fi
    if jq -e "$expr" "$verdict" >/dev/null 2>&1; then
        log_ok "$label"
    else
        local snippet
        snippet="$(jq -c '{result, missing, warn, ok_count, languages}' "$verdict" 2>/dev/null || echo '<unreadable>')"
        log_fail "$label" "assertion failed: $expr  |  got: $snippet"
    fi
}

# --- Cases -----------------------------------------------------------------

echo "fabcheck fixture tests"

# Detect whether the active env has importlib.metadata populated. Both the
# ok-precise and missing-precise cases depend on precise mode being reachable,
# which means this test run must be under an env that exposes pillow.
HAVE_PRECISE="false"
if command -v python3 >/dev/null 2>&1; then
    if python3 -c 'import json, sys; from importlib.metadata import packages_distributions; m=packages_distributions(); sys.exit(0 if m.get("PIL") else 1)' 2>/dev/null; then
        HAVE_PRECISE="true"
    fi
fi

# 1. ok-precise: Pillow declared, PIL imported. precise mode -> ok.
if [ "$HAVE_PRECISE" = "true" ]; then
    T="$(prepare_and_run ok-precise --language python)"
    assert_json "$T/.tmp-fabcheck/verdict.json" \
        '.result=="pass" and .missing==0 and .languages.python.resolution_mode=="precise" and (.findings|map(select(.symbol=="PIL" and .level=="ok"))|length)>=1' \
        "ok-precise: PIL resolves via pillow dist"
else
    log_skip "ok-precise" "env has no PIL->pillow mapping (install pillow in the active env)"
fi

# 2. missing-precise: Pillow NOT declared, PIL imported. precise mode -> missing.
if [ "$HAVE_PRECISE" = "true" ]; then
    T="$(prepare_and_run missing-precise --language python)"
    assert_json "$T/.tmp-fabcheck/verdict.json" \
        '.result=="fail" and .missing>=1 and .languages.python.resolution_mode=="precise" and (.findings|map(select(.symbol=="PIL" and .level=="missing"))|length)>=1' \
        "missing-precise: PIL flagged because pillow is undeclared"
else
    log_skip "missing-precise" "env has no PIL->pillow mapping"
fi

# 3. hallucinated: fake package not in stdlib, not local, not in any env dist.
T="$(prepare_and_run hallucinated --language python)"
assert_json "$T/.tmp-fabcheck/verdict.json" \
    '.result=="fail" and .missing>=1 and (.findings|map(select(.symbol=="totally_fake_package_xyz" and .level=="missing"))|length)>=1' \
    "hallucinated: fake top-level module flagged"

# 4. stdlib-only: every import is stdlib. No missing.
T="$(prepare_and_run stdlib-only --language python)"
assert_json "$T/.tmp-fabcheck/verdict.json" \
    '.result=="pass" and .missing==0 and .warn==0 and (.findings|all(.level=="ok" and .message=="stdlib"))' \
    "stdlib-only: __future__ / array / os / json all classified stdlib"

# 5. relative-import: from . / from .helpers — treat as local.
T="$(prepare_and_run relative-import --language python)"
assert_json "$T/.tmp-fabcheck/verdict.json" \
    '.result=="pass" and .missing==0 and (.findings|map(select(.message=="relative import"))|length)>=1' \
    "relative-import: leading-dot imports classified as ok"

# 6. fallback: python3 unavailable -> warn (resolution_mode=fallback).
#    Simulated by prepending a shim that exits 1 as python3. The shim is a
#    sh script; if the platform refuses to execute it, skip cleanly.
SHIM_DIR="$WORK_ROOT/_shim"
rm -rf "$SHIM_DIR"
mkdir -p "$SHIM_DIR"
cat > "$SHIM_DIR/python3" <<'SHIM'
#!/bin/sh
exit 1
SHIM
chmod +x "$SHIM_DIR/python3" 2>/dev/null || true
if PATH="$SHIM_DIR" command -v python3 >/dev/null 2>&1 && ! PATH="$SHIM_DIR" python3 -c '' 2>/dev/null; then
    # Shim works as expected. Run the missing-precise fixture again (reuse
    # the prepared dir) with the shim prepended to PATH — same source files,
    # but no env metadata => fallback mode.
    FB_WORK="$WORK_ROOT/fallback"
    rm -rf "$FB_WORK"
    mkdir -p "$FB_WORK"
    cp -r "$FIXTURES/missing-precise/." "$FB_WORK/"
    (
        cd "$FB_WORK"
        git init -q
        git -c core.autocrlf=false -c user.email=test@fabcheck -c user.name=test add -A 2>/dev/null
        git -c core.autocrlf=false -c user.email=test@fabcheck -c user.name=test commit -q -m init >/dev/null
        PATH="$SHIM_DIR:$PATH" bash "$FABCHECK" --language python >/dev/null 2>&1 || true
    )
    assert_json "$FB_WORK/.tmp-fabcheck/verdict.json" \
        '.languages.python.resolution_mode=="fallback" and .languages.python.env_metadata_available==false and (.findings|map(select(.symbol=="PIL" and .level=="warn"))|length)>=1' \
        "fallback: python3 unavailable -> warn with fallback mode"
else
    log_skip "fallback" "python3 shim not executable on this platform"
fi

# --- Report ----------------------------------------------------------------

echo
echo "fabcheck fixture tests: $pass_count passed, $fail_count failed, $skip_count skipped"
echo "(working dirs preserved under $WORK_ROOT — see common/tmp-dirs.md)"
if [ "$fail_count" -gt 0 ]; then
    printf 'Failed cases: %s\n' "${FAILED_CASES[*]}"
    exit 1
fi
exit 0
