# Generated By: Claude Code (Claude Opus 4.6)
# Optional target: install CLI tools globally via pipx.
# Copy to make/pipx.mk and add to Makefile: -include make/pipx.mk
# Requires: python3 -m pip install --user pipx

.PHONY: pipx pipx-uninstall

# PROJECT_NAME is the distribution name from [project] name in pyproject.toml.
# This may differ from PACKAGE_NAME (the Python module name) — e.g., my-tool vs my_tool.
PROJECT_NAME ?= $(PACKAGE_NAME)

pipx:  ## Install globally via pipx
	python3 -m pipx install .

pipx-uninstall:  ## Uninstall global pipx install
	python3 -m pipx uninstall $(PROJECT_NAME)
