# Generated By: Claude Code (Claude Opus 4.7)
# Standard test-* collection. Pulled out of the root Makefile to keep it
# uncluttered. Copy to make/test.mk and add to root Makefile:
#   -include make/test.mk

.PHONY: test-unit test-coverage test-format test-lint test-typecheck test-complexity test-mutation

test-unit: install-dev  ## Run pytest
	$(PYTHON) -m pytest

test-coverage: install-dev  ## Run pytest with 80% coverage threshold
	$(PYTHON) -m pytest --cov=$(PACKAGE_NAME) --cov-report=term --cov-fail-under=80

test-format: install-dev  ## Check formatting (exits non-zero if changes needed)
	$(PYTHON) -m black --check $(PACKAGE_NAME) tests

test-lint: install-dev  ## Lint with flake8
	$(PYTHON) -m flake8 --max-line-length=88 --extend-ignore=E203,W503 $(PACKAGE_NAME) tests

test-typecheck: install-dev  ## Type check with mypy
	$(PYTHON) -m mypy $(PACKAGE_NAME)

test-complexity: install-dev  ## Cyclomatic complexity check (xenon)
	$(PYTHON) -m xenon $(PACKAGE_NAME) --max-absolute B --max-modules B --max-average A

test-mutation: install-dev  ## Run mutation testing (not part of check)
	$(PYTHON) -m mutmut run --CI --paths-to-mutate "$(PACKAGE_NAME)"
