# Generated By: Claude Code (Claude Opus 4.6)

.PHONY: version-check

version-check:  ## Validate semver: format, sources match, version bumped vs mainline
	@bash scripts/version-check.sh "$(VERSION_FILE)" $(VERSION_DIRS)
