#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Analyze document link depths from README.md and CLAUDE.md to all repo files."""

import argparse
import os
import re
import subprocess
import sys
from collections import deque


def find_tracked_md_files(repo_root: str) -> list[str]:
    """Find all tracked .md files using git ls-files (respects .gitignore)."""
    result = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard"],
        capture_output=True,
        text=True,
        cwd=repo_root,
    )
    return sorted(
        line for line in result.stdout.strip().splitlines()
        if line and not line.startswith(".github")
    )


def extract_links(filepath: str, repo_root: str) -> list[str]:
    """Extract relative file links from a markdown file."""
    rel_path = os.path.relpath(filepath, repo_root)
    file_dir = os.path.dirname(rel_path)

    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
    except (UnicodeDecodeError, FileNotFoundError):
        return []

    # Match markdown links: [text](path) — skip external URLs, anchors, images
    pattern = r"\[[^\]]*\]\(([^)]+)\)"
    links = []
    for match in re.finditer(pattern, content):
        target = match.group(1)
        # Skip external URLs
        if target.startswith(("http://", "https://", "mailto:")):
            continue
        # Skip pure anchors
        if target.startswith("#"):
            continue
        # Strip anchor from path
        target = target.split("#")[0]
        if not target:
            continue
        # Resolve relative to the file's directory
        resolved = os.path.normpath(os.path.join(file_dir, target))
        links.append(resolved)

    return links


def build_link_graph(repo_root: str, all_files: list[str]) -> dict[str, list[str]]:
    """Build a directed graph of file -> files it links to."""
    graph: dict[str, list[str]] = {}
    all_files_set = set(all_files)

    for f in all_files:
        full = os.path.join(repo_root, f)
        raw_links = extract_links(full, repo_root)
        resolved = []
        for link in raw_links:
            if link in all_files_set:
                resolved.append(link)
            elif link + "/README.md" in all_files_set:
                resolved.append(link + "/README.md")
            elif link.endswith("/"):
                candidate = link + "README.md"
                if candidate in all_files_set:
                    resolved.append(candidate)
                dir_path = link.rstrip("/") + "/"
                for af in all_files:
                    if af.startswith(dir_path):
                        resolved.append(af)
        graph[f] = list(dict.fromkeys(resolved))

    return graph


def bfs_depths(graph: dict[str, list[str]], start: str) -> dict[str, int]:
    """BFS from start node, return depth to each reachable node."""
    depths: dict[str, int] = {start: 1}
    queue = deque([(start, 1)])

    while queue:
        node, depth = queue.popleft()
        for neighbor in graph.get(node, []):
            if neighbor not in depths:
                depths[neighbor] = depth + 1
                queue.append((neighbor, depth + 1))

    return depths


# Files that are not documentation and don't need to be reachable from
# entry points. Only root-level infra and scripts.
EXCLUDED_PREFIXES = (
    ".",
    "scripts/",
)
EXCLUDED_EXACT = {
    "ANALYSIS.md",
    "LICENSE",
    "Makefile",
    "pyproject.toml",
}


def is_excluded(filepath: str) -> bool:
    """Check if a file is excluded from reachability requirements."""
    if filepath in EXCLUDED_EXACT:
        return True
    basename = os.path.basename(filepath)
    if basename.startswith("."):
        return True
    return filepath.startswith(EXCLUDED_PREFIXES)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="Exit non-zero if any non-excluded file is unreachable from CLAUDE.md",
    )
    args = parser.parse_args()

    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    all_files = find_tracked_md_files(repo_root)
    graph = build_link_graph(repo_root, all_files)

    readme_depths = bfs_depths(graph, "README.md")
    claude_depths = bfs_depths(graph, "CLAUDE.md")

    # Build table
    lines = []
    lines.append("# Document Depth Analysis")
    lines.append("")
    lines.append("Depth = shortest link-chain from entry point to file.")
    lines.append("Entry points have depth 1. Depth x = no path exists.")
    lines.append("")
    lines.append("| File | README.md | CLAUDE.md |")
    lines.append("|------|-----------|-----------|")

    unreachable = []
    for f in all_files:
        r_depth = readme_depths.get(f, "x")
        c_depth = claude_depths.get(f, "x")
        lines.append(f"| `{f}` | {r_depth} | {c_depth} |")
        if not is_excluded(f):
            if f not in readme_depths:
                unreachable.append((f, "README.md"))
            if f not in claude_depths:
                unreachable.append((f, "CLAUDE.md"))

    output = "\n".join(lines) + "\n"

    output_path = os.path.join(repo_root, "ANALYSIS.md")
    with open(output_path, "w") as out:
        out.write(output)

    print(f"Wrote {output_path} ({len(all_files)} files)")

    r_reachable = sum(1 for f in all_files if f in readme_depths)
    c_reachable = sum(1 for f in all_files if f in claude_depths)
    print(f"Reachable from README.md: {r_reachable}/{len(all_files)}")
    print(f"Reachable from CLAUDE.md: {c_reachable}/{len(all_files)}")

    # CLAUDE.md must link every non-excluded file directly (depth 2)
    too_deep = []
    for f in all_files:
        if is_excluded(f) or f == "CLAUDE.md":
            continue
        depth = claude_depths.get(f)
        if depth is None or depth > 2:
            too_deep.append((f, depth))

    failures = unreachable + [(f, f"CLAUDE.md (depth {d}, expected 2)") for f, d in too_deep]

    if args.check and failures:
        print(f"\nERROR: {len(failures)} issue(s):")
        for filepath, detail in failures:
            if isinstance(detail, str) and detail.startswith("CLAUDE"):
                print(f"  {filepath} — {detail}")
            else:
                print(f"  {filepath} — not reachable from {detail}")
        sys.exit(1)


if __name__ == "__main__":
    main()
