#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Check local markdown links and anchors. Exit 1 if any are broken."""

import re
import sys
from pathlib import Path

LINK_PATTERN = re.compile(r"\[([^\]]*)\]\(([^)]+)\)")
HEADING_PATTERN = re.compile(r"^#{1,6}\s+(.+)$", re.MULTILINE)


def heading_to_anchor(heading):
    """Convert a markdown heading to a GitHub-style anchor slug."""
    text = heading.strip()
    # Remove inline markdown: bold, italic, code, links
    text = re.sub(r"[*_`]", "", text)
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    text = text.lower()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s]+", "-", text)
    text = text.rstrip("-")
    return text


def get_anchors(path):
    """Extract all heading anchors from a markdown file."""
    try:
        content = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return set()
    return {heading_to_anchor(m) for m in HEADING_PATTERN.findall(content)}


def check_file(filepath, root):
    """Check all local links in a single markdown file. Return list of errors."""
    errors = []
    try:
        content = filepath.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return errors

    in_code_block = False
    for line_num, line in enumerate(content.splitlines(), 1):
        if line.strip().startswith("```"):
            in_code_block = not in_code_block
            continue
        if in_code_block:
            continue
        # Strip inline code spans before matching links
        line_no_code = re.sub(r"`[^`]+`", "", line)
        for match in LINK_PATTERN.finditer(line_no_code):
            target = match.group(2).strip()

            # Skip external URLs, special schemes, and non-path targets
            if re.match(r"^(https?://|mailto:|#$)", target):
                continue
            if target in ("...", ):
                continue
            # Skip glob patterns used as descriptive text
            if "*" in target:
                continue

            # Split target into path and optional fragment
            if "#" in target:
                if target.startswith("#"):
                    # Self-referencing anchor
                    fragment = target[1:]
                    anchors = get_anchors(filepath)
                    if fragment and fragment not in anchors:
                        errors.append((filepath, line_num, target, "anchor not found"))
                    continue
                path_part, fragment = target.split("#", 1)
            else:
                path_part, fragment = target, None

            # Resolve relative to the file's directory
            resolved = (filepath.parent / path_part).resolve()

            if not resolved.exists():
                errors.append((filepath, line_num, target, "file/dir not found"))
            elif fragment:
                anchors = get_anchors(resolved)
                if fragment not in anchors:
                    errors.append((filepath, line_num, target, "anchor not found"))

    return errors


def main():
    root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(".")
    root = root.resolve()

    md_files = sorted(
        p for p in root.rglob("*.md")
        if ".git" not in p.parts
    )

    all_errors = []
    for f in md_files:
        all_errors.extend(check_file(f, root))

    if all_errors:
        for filepath, line_num, target, reason in all_errors:
            rel = filepath.relative_to(root)
            print(f"{rel}:{line_num}: {reason} -> {target}")
        print(f"\n{len(all_errors)} broken link(s) found.")
        sys.exit(1)
    else:
        print(f"Checked {len(md_files)} files, all links OK.")


if __name__ == "__main__":
    main()
