#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Check local markdown links and anchors. Exit 1 if any are broken."""

import os
import re
import sys
from pathlib import Path

LINK_PATTERN = re.compile(r"\[([^\]]*)\]\(([^)]+)\)")
HEADING_PATTERN = re.compile(r"^#{1,6}\s+(.+)$", re.MULTILINE)

# Mirrors the .gitignore patterns relevant to .md enumeration. Avoids
# `git ls-files` because actions/checkout@v4 in act on Windows leaves
# .git/ missing in the container — git would fail at the FS boundary.
EXCLUDED_DIR_PARTS = frozenset({
    ".git", ".work", "__pycache__", "dist", ".eggs",
    "venv", ".venv", "env", ".idea", ".vscode",
    ".pytest_cache", "htmlcov", ".mypy_cache",
})


def _is_excluded(rel_path: Path) -> bool:
    for part in rel_path.parts:
        if part in EXCLUDED_DIR_PARTS:
            return True
        if part.startswith(".tmp-"):
            return True
    name = rel_path.name
    if name == "ANALYSIS.md":
        return True
    if name.startswith("Findings-") or name.startswith("Report-"):
        return True
    return False


def heading_to_anchor(heading):
    """Convert a markdown heading to a GitHub-style anchor slug."""
    text = heading.strip()
    # Remove inline markdown: bold, code, links.
    # Underscores are intentionally NOT stripped — GitHub preserves them
    # inside words (e.g., `PY_SYS` -> `py_sys` in the slug). Stripping `_`
    # here diverges from GitHub's actual anchor generation and breaks links
    # to any heading that contains an underscored identifier.
    text = re.sub(r"[*`]", "", text)
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    text = text.lower()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s]+", "-", text)
    text = text.rstrip("-")
    return text


def get_anchors(path):
    """Extract all heading anchors from a markdown file."""
    try:
        content = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return set()
    return {heading_to_anchor(m) for m in HEADING_PATTERN.findall(content)}


def check_file(filepath, root):
    """Check all local links in a single markdown file. Return list of errors."""
    errors = []
    try:
        content = filepath.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return errors

    in_code_block = False
    for line_num, line in enumerate(content.splitlines(), 1):
        if line.strip().startswith("```"):
            in_code_block = not in_code_block
            continue
        if in_code_block:
            continue
        # Strip inline code spans before matching links
        line_no_code = re.sub(r"`[^`]+`", "", line)
        for match in LINK_PATTERN.finditer(line_no_code):
            target = match.group(2).strip()

            # Skip external URLs, special schemes, and non-path targets
            if re.match(r"^(https?://|mailto:|#$)", target):
                continue
            if target in ("...", ):
                continue
            # Skip glob patterns used as descriptive text
            if "*" in target:
                continue

            # Split target into path and optional fragment
            if "#" in target:
                if target.startswith("#"):
                    # Self-referencing anchor
                    fragment = target[1:]
                    anchors = get_anchors(filepath)
                    if fragment and fragment not in anchors:
                        errors.append((filepath, line_num, target, "anchor not found"))
                    continue
                path_part, fragment = target.split("#", 1)
            else:
                path_part, fragment = target, None

            # Resolve relative to the file's directory
            resolved = (filepath.parent / path_part).resolve()

            if not resolved.exists():
                errors.append((filepath, line_num, target, "file/dir not found"))
            elif fragment:
                anchors = get_anchors(resolved)
                if fragment not in anchors:
                    errors.append((filepath, line_num, target, "anchor not found"))

    return errors


def main():
    root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(os.getcwd())
    md_files = sorted(
        p for p in root.rglob("*.md")
        if not _is_excluded(p.relative_to(root))
    )

    all_errors = []
    for f in md_files:
        all_errors.extend(check_file(f, root))

    if all_errors:
        for filepath, line_num, target, reason in all_errors:
            rel = filepath.relative_to(root)
            print(f"{rel}:{line_num}: {reason} -> {target}")
        print(f"\n{len(all_errors)} broken link(s) found.")
        sys.exit(1)
    else:
        print(f"Checked {len(md_files)} files, all links OK.")


if __name__ == "__main__":
    main()
