#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Analyze document link depths from README.md and CLAUDE.md to all repo files."""

import argparse
import os
import re
import subprocess
import sys
from collections import deque


def find_tracked_files(repo_root: str) -> list[str]:
    """Find all tracked files using git ls-files (respects .gitignore)."""
    result = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard"],
        capture_output=True,
        text=True,
        cwd=repo_root,
    )
    return sorted(
        line for line in result.stdout.strip().splitlines()
        if line and not line.startswith(".github")
    )


def extract_links(filepath: str, repo_root: str) -> list[str]:
    """Extract relative file links from a markdown file."""
    rel_path = os.path.relpath(filepath, repo_root)
    file_dir = os.path.dirname(rel_path)

    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
    except (UnicodeDecodeError, FileNotFoundError):
        return []

    # Match markdown links: [text](path) — skip external URLs, anchors, images
    pattern = r"\[[^\]]*\]\(([^)]+)\)"
    links = []
    for match in re.finditer(pattern, content):
        target = match.group(1)
        # Skip external URLs
        if target.startswith(("http://", "https://", "mailto:")):
            continue
        # Skip pure anchors
        if target.startswith("#"):
            continue
        # Strip anchor from path
        target = target.split("#")[0]
        if not target:
            continue
        # Handle absolute paths (rooted at repo root)
        if target.startswith("/"):
            resolved = os.path.normpath(target.lstrip("/"))
        else:
            resolved = os.path.normpath(os.path.join(file_dir, target))
        links.append(resolved)

    return links


def build_link_graph(repo_root: str, all_files: list[str]) -> dict[str, list[str]]:
    """Build a directed graph of file -> files it links to."""
    graph: dict[str, list[str]] = {}
    all_files_set = set(all_files)

    for f in all_files:
        full = os.path.join(repo_root, f)
        raw_links = extract_links(full, repo_root)
        resolved = []
        for link in raw_links:
            if link in all_files_set:
                resolved.append(link)
            elif link + "/README.md" in all_files_set:
                resolved.append(link + "/README.md")
            elif link.endswith("/"):
                candidate = link + "README.md"
                if candidate in all_files_set:
                    resolved.append(candidate)
                dir_path = link.rstrip("/") + "/"
                for af in all_files:
                    if af.startswith(dir_path):
                        resolved.append(af)
        graph[f] = list(dict.fromkeys(resolved))

    return graph


def bfs_depths(graph: dict[str, list[str]], start: str) -> dict[str, int]:
    """BFS from start node, return depth to each reachable node."""
    depths: dict[str, int] = {start: 1}
    queue = deque([(start, 1)])

    while queue:
        node, depth = queue.popleft()
        for neighbor in graph.get(node, []):
            if neighbor not in depths:
                depths[neighbor] = depth + 1
                queue.append((neighbor, depth + 1))

    return depths


# Files that are not documentation and don't need to be reachable from
# entry points. Only root-level infra and scripts.
EXCLUDED_PREFIXES = (
    ".",
    "scripts/",
)
EXCLUDED_EXACT = {
    "ANALYSIS.md",
    "LICENSE",
    "Makefile",
    "pyproject.toml",
}


def is_excluded(filepath: str) -> bool:
    """Check if a file is excluded from reachability requirements."""
    if filepath in EXCLUDED_EXACT:
        return True
    basename = os.path.basename(filepath)
    if basename.startswith("."):
        return True
    return filepath.startswith(EXCLUDED_PREFIXES)


# Entry points for reachability analysis.
# CLAUDE.md is the comprehensive index and must directly link every content file.
# README.md also links docs for human readers.
ENTRY_POINTS = ["CLAUDE.md", "README.md"]
DIRECT_LINK_ENTRY = "CLAUDE.md"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="Exit non-zero if any non-excluded file is unreachable or not "
             f"directly linked from {DIRECT_LINK_ENTRY}",
    )
    args = parser.parse_args()

    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    all_files = find_tracked_files(repo_root)
    graph = build_link_graph(repo_root, all_files)

    entry_set = set(ENTRY_POINTS)
    depths_by_entry = {}
    for entry in ENTRY_POINTS:
        if entry in set(all_files):
            depths_by_entry[entry] = bfs_depths(graph, entry)

    # Build table
    lines = []
    lines.append("# Document Depth Analysis")
    lines.append("")
    lines.append("Depth = shortest link-chain from entry point to file.")
    lines.append("Entry points have depth 1. Depth x = no path exists.")
    lines.append("")
    header = "| File | " + " | ".join(depths_by_entry.keys()) + " |"
    sep = "|------" + "|-----------|" * len(depths_by_entry)
    lines.append(header)
    lines.append(sep)

    unreachable = []
    for f in all_files:
        cols = []
        for entry, depths in depths_by_entry.items():
            d = depths.get(f, "x")
            cols.append(str(d))
        lines.append(f"| `{f}` | " + " | ".join(cols) + " |")
        if not is_excluded(f) and f not in entry_set:
            for entry, depths in depths_by_entry.items():
                if f not in depths:
                    unreachable.append((f, entry))

    output = "\n".join(lines) + "\n"

    content_files = [f for f in all_files if not is_excluded(f) and f not in entry_set]

    if not args.check:
        output_path = os.path.join(repo_root, "ANALYSIS.md")
        with open(output_path, "w") as out:
            out.write(output)
        print(f"Wrote {output_path} ({len(content_files)} content files, "
              f"{len(all_files) - len(content_files)} excluded)")

    for entry, depths in depths_by_entry.items():
        reachable = sum(1 for f in content_files if f in depths)
        print(f"Reachable from {entry}: {reachable}/{len(content_files)} content files")

    # Direct-link entry must link every non-excluded file directly (depth 2)
    direct_depths = depths_by_entry.get(DIRECT_LINK_ENTRY, {})
    too_deep = []
    for f in all_files:
        if is_excluded(f) or f in entry_set:
            continue
        depth = direct_depths.get(f)
        if depth is None or depth > 2:
            too_deep.append((f, depth))

    failures = unreachable + [
        (f, f"{DIRECT_LINK_ENTRY} (depth {d}, expected 2)")
        for f, d in too_deep
    ]

    if args.check and failures:
        print(f"\nERROR: {len(failures)} issue(s):")
        for filepath, detail in failures:
            if isinstance(detail, str) and detail.startswith(DIRECT_LINK_ENTRY):
                print(f"  {filepath} — {detail}")
            else:
                print(f"  {filepath} — not reachable from {detail}")
        sys.exit(1)


if __name__ == "__main__":
    main()
