#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Analyze document link depths from entry points to all repo content files."""

import argparse
import os
import re
import sys
from collections import deque
from pathlib import Path

# --- Repo-specific configuration ---

# Entry points for reachability analysis.
ENTRY_POINTS = ["CLAUDE.md", "README.md"]

# The entry point that enforces max-depth. Must directly or transitively
# link every content file within the depth limit.
DIRECT_LINK_ENTRY = "CLAUDE.md"

# Files excluded from reachability requirements (infra, scripts, etc.).
EXCLUDED_PREFIXES = (
    ".",
    ".github/",
    "scripts/",
    "tests/",
)
EXCLUDED_EXACT = {
    "ANALYSIS.md",
    "LICENSE",
    "Makefile",
    "pyproject.toml",
}

# Mirrors the .gitignore patterns relevant to enumeration. Avoids
# `git ls-files` because actions/checkout@v4 in act on Windows leaves
# .git/ missing in the container — git would fail and the script
# would silently report 0 content files.
_EXCLUDED_DIR_PARTS = frozenset({
    ".git", ".work", "__pycache__", "dist", ".eggs",
    "venv", ".venv", "env", ".idea", ".vscode",
    ".pytest_cache", "htmlcov", ".mypy_cache",
})

# --- End repo-specific configuration ---


def _is_enum_excluded(rel_path: Path) -> bool:
    for part in rel_path.parts:
        if part in _EXCLUDED_DIR_PARTS:
            return True
        if part.startswith(".tmp-"):
            return True
    name = rel_path.name
    if name == "ANALYSIS.md":
        return True
    if name.startswith("Findings-") or name.startswith("Report-"):
        return True
    return False


def find_tracked_files(repo_root: str) -> list[str]:
    """Enumerate repo files, honouring the .gitignore patterns this tool
    cares about. Avoids the `git ls-files` dependency so the script works
    inside CI containers that may not preserve .git/ (e.g. act on Windows)."""
    root = Path(repo_root)
    files: list[str] = []
    for p in root.rglob("*"):
        if not p.is_file():
            continue
        rel = p.relative_to(root)
        if _is_enum_excluded(rel):
            continue
        files.append(rel.as_posix())
    return sorted(files)


def extract_links(filepath: str, repo_root: str) -> list[str]:
    """Extract relative file links from a markdown file."""
    rel_path = os.path.relpath(filepath, repo_root)
    file_dir = os.path.dirname(rel_path)

    try:
        with open(filepath, encoding="utf-8") as f:
            content = f.read()
    except (UnicodeDecodeError, FileNotFoundError):
        return []

    pattern = r"\[[^\]]*\]\(([^)]+)\)"
    links = []
    for match in re.finditer(pattern, content):
        target = match.group(1)
        if target.startswith(("http://", "https://", "mailto:")):
            continue
        if target.startswith("#"):
            continue
        target = target.split("#")[0]
        if not target:
            continue
        if target.startswith("/"):
            resolved = os.path.normpath(target.lstrip("/"))
        else:
            resolved = os.path.normpath(os.path.join(file_dir, target))
        links.append(resolved.replace("\\", "/"))

    return links


def build_link_graph(repo_root: str, all_files: list[str]) -> dict[str, list[str]]:
    """Build a directed graph of file -> files it links to."""
    graph: dict[str, list[str]] = {}
    all_files_set = set(all_files)

    for f in all_files:
        if not f.endswith(".md"):
            continue
        full = os.path.join(repo_root, f)
        raw_links = extract_links(full, repo_root)
        resolved = []
        for link in raw_links:
            if link in all_files_set:
                resolved.append(link)
            elif link + "/README.md" in all_files_set:
                resolved.append(link + "/README.md")
            elif link.endswith("/"):
                candidate = link + "README.md"
                if candidate in all_files_set:
                    resolved.append(candidate)
                dir_path = link.rstrip("/") + "/"
                for af in all_files:
                    if af.startswith(dir_path):
                        resolved.append(af)
        graph[f] = list(dict.fromkeys(resolved))

    return graph


def bfs_depths(graph: dict[str, list[str]], start: str) -> dict[str, int]:
    """BFS from start node, return depth to each reachable node."""
    depths: dict[str, int] = {start: 1}
    queue = deque([(start, 1)])

    while queue:
        node, depth = queue.popleft()
        for neighbor in graph.get(node, []):
            if neighbor not in depths:
                depths[neighbor] = depth + 1
                queue.append((neighbor, depth + 1))

    return depths


def is_content_file(filepath: str) -> bool:
    """Check if a file is content that must be reachable from entry points."""
    if filepath in EXCLUDED_EXACT:
        return False
    basename = os.path.basename(filepath)
    if basename.startswith("."):
        return False
    if filepath.startswith(EXCLUDED_PREFIXES):
        return False
    return True


def build_depth_table(
    all_files: list[str],
    depths_by_entry: dict[str, dict[str, int]],
    entry_set: set[str],
) -> tuple[list[str], list[tuple[str, str]]]:
    """Build a markdown depth table and collect unreachable files."""
    lines = [
        "# Document Depth Analysis",
        "",
        "Depth = shortest link-chain from entry point to file.",
        "Entry points have depth 1. Depth x = no path exists.",
        "",
        "| File | " + " | ".join(depths_by_entry.keys()) + " |",
        "|------" + "|-----------|" * len(depths_by_entry),
    ]

    unreachable = []
    for f in all_files:
        cols = [str(depths.get(f, "x")) for _entry, depths in depths_by_entry.items()]
        lines.append(f"| `{f}` | " + " | ".join(cols) + " |")
        if is_content_file(f) and f not in entry_set:
            for entry, depths in depths_by_entry.items():
                if f not in depths:
                    unreachable.append((f, entry))

    return lines, unreachable


def find_failures(
    content_files: list[str],
    depths_by_entry: dict[str, dict[str, int]],
    max_depth: int,
    unreachable: list[tuple[str, str]],
) -> list[tuple[str, str]]:
    """Find content files that are unreachable or exceed max depth."""
    direct_depths = depths_by_entry.get(DIRECT_LINK_ENTRY, {})
    too_deep = [
        (f, direct_depths.get(f)) for f in content_files if direct_depths.get(f) is None or direct_depths[f] > max_depth
    ]

    return unreachable + [(f, f"{DIRECT_LINK_ENTRY} (depth {d}, max {max_depth})") for f, d in too_deep]


def main() -> None:
    """Run reachability check."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if any content file is unreachable or exceeds max depth",
    )
    parser.add_argument(
        "--max-depth",
        type=int,
        default=2,
        help="Maximum allowed depth from direct-link entry (default: 2)",
    )
    args = parser.parse_args()

    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    all_files = find_tracked_files(repo_root)
    graph = build_link_graph(repo_root, all_files)

    entry_set = set(ENTRY_POINTS)
    depths_by_entry = {entry: bfs_depths(graph, entry) for entry in ENTRY_POINTS if entry in set(all_files)}

    content_files = [f for f in all_files if is_content_file(f) and f not in entry_set]
    lines, unreachable = build_depth_table(all_files, depths_by_entry, entry_set)

    if not args.check:
        output_path = os.path.join(repo_root, "ANALYSIS.md")
        with open(output_path, "w") as out:
            out.write("\n".join(lines) + "\n")
        print(f"Wrote {output_path} ({len(content_files)} content files, {len(all_files) - len(content_files)} excluded)")

    for entry, depths in depths_by_entry.items():
        reachable = sum(1 for f in content_files if f in depths)
        print(f"Reachable from {entry}: {reachable}/{len(content_files)} content files")

    failures = find_failures(content_files, depths_by_entry, args.max_depth, unreachable)
    if args.check and failures:
        print(f"\nERROR: {len(failures)} issue(s):")
        for filepath, detail in failures:
            if isinstance(detail, str) and detail.startswith(DIRECT_LINK_ENTRY):
                print(f"  {filepath} — {detail}")
            else:
                print(f"  {filepath} — not reachable from {detail}")
        sys.exit(1)


if __name__ == "__main__":
    main()
